name: build client image

on:
  workflow_dispatch:
  push:
    paths:
      - 'client/**'
      - '.github/workflows/client.yaml'
    branches:
      - main

jobs: 
  build:
    name: 'client:build'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          context: ./client
          file: ./client/Dockerfile
          platforms: linux/arm64, linux/amd64
          push: true
          tags: ghcr.io/elliemehl/kube_app:client-${{ github.sha }}
  test:
    name: 'client:test'
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull and run tests
        run: |
          docker pull ghcr.io/elliemehl/kube_app:client-${{ github.sha }}
          docker run -d -p 8080:8080 -e APP_PORT=8080 ghcr.io/elliemehl/kube_app:client-${{ github.sha }}
          sleep 10
          curl localhost:8080/
          exit $?
      - name: Push image
        run: |
          docker tag ghcr.io/elliemehl/kube_app:client-${{ github.sha }} ghcr.io/elliemehl/kube_app:client
          docker push ghcr.io/elliemehl/kube_app:client

