name: build server image

on:
  workflow_dispatch:
  push:
    paths:
      - 'server/**'
      - '.github/workflows/server.yaml'
    branches:
      - main

jobs: 
  build:
    name: 'server:build'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: gher.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          context: ./server
          file: ./server/Dockerfile
          platforms: linux/arm64, linux/amd64
          push: true
          tags: ghcr.io/elliemehl/KubeApp:server-${{ github.sha }}
tests:
  name: 'server:test'
  runs-on: ubuntu-latest
  needs: [ build ]
  steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-qemu-action@v2
    - uses: docker/setup-buildx-action@v2
    - uses: docker/login-action@v2
      with:
        registry: gher.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Pull and run tests
      run: |
        docker pull ghcr.io/elliemehl/KubeApp:server-${{ github.sha }}
        docker run -d -p 8080:8080 -e APP_PORT=8080 ghcr.io/elliemehl/KubeApp:server-${{ github.sha }}
        sleep 10
        curl localhost:8080/api/status
        exit $?
    - name: Push image
      run: |
        docker tag ghcr.io/elliemehl/KubeApp:server-${{ github.sha }} ghcr.io/elliemehl/KubeApp:server
        docker push ghcr.io/elliemehl/KubeApp:server

